--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iZeaoGamer/PlayerVaults-Test
branches:
- master
projects:
  PlayerVaults-Test:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^3.1.0
      - src: poggit/libasynql/libasynql
        version: ^3.1.1
...
