name: PlayerVaults
main: muqsit\playervaults\PlayerVaults
api: 3.0.0
version: 3.2.1
commands:
  playervault:
    default: true
    aliases: ["pv"]
permissions:
  vaults.1:
    default: true
  vaults.others.edit:
    default: op
  vaults.others.view:
    default: op
